name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  pythonforensicstorelib:
    name: Python forensicstore
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest] # , windows-latest
        python-version: ['3.6', '3.7', '3.8', '3.9'] # , '3.10'
    steps:

    # Setup
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install pylint==2.7.0 pytest==6.2.0 pytest-cov

    - run: pip install .

    # Lint and test pyforensicstore
    - run: pylint forensicstore --rcfile test/python/.pylintrc
    - run: pytest -v --cov-report=xml --cov=forensicstore .
      shell: bash
      working-directory: test/python

    - name: Upload coverage
      env:
        CI: "true"
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash) -f test/python/coverage.xml
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.9
      shell: bash

    # Test pyforensicstore command
    - name: Set system path
      run: echo $PWD >> $GITHUB_PATH
      shell: bash
    - name: Setup node
      uses: actions/setup-node@v3
      with: {node-version: '10.x'}
    - name: Install bats
      run: npm install -g bats
    - name: Bats python test
      run: bats test/bats/forensicstore.bats test/bats/forensicstore_validate.bats
      shell: bash
